# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9efde6f8397fa7ae2070e8894c9c348bdb40592475f95220ad4a4c39c737c59913961220ccb99ab1fb113a65b0adb2ec1ffeffa3bc7b78fe882d8f2c83565b55

test:
  secret_key_base: 5a3f695648f091e844f6f8b28fc608f2f9df4ba1b2343c21bd965923bafa163d24ae6fb054c6af712e3802ade1995b089af7f7d4f4d10d10c435d06419e2ede4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
